import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {School, Search, ShieldCheck, Users, GraduationCap, Wallet, MessageSquare, Menu, X, ChevronRight, CheckCircle, Clock, AlertTriangle, Plus, LogOut, LayoutDashboard, BookOpen, CalendarCheck, Receipt, Settings, Boxes, FileText, UserPlus, CalendarDays, Upload, ClipboardList, UserCheck, XCircle, Eye, Trash2} from 'lucide-react';
import './styles.css';

const roles={
  'System Admin':['dashboard','schools','settings'],
  'Principal':['dashboard','admissions','students','teachers','attendance','marks','finance','spaces','resources','notifications','calendar','reports','settings'],
  'Deputy Principal':['dashboard','admissions','students','teachers','attendance','marks','finance','spaces','resources','notifications','calendar','reports'],
  'Teacher':['dashboard','students','attendance','marks','calendar'],
  'Accountant':['dashboard','finance'],
  'Secretary':['dashboard','notifications','calendar'],
  'Parent':['dashboard','schools','children','applications','attendance','marks','fees','notifications']
};
const navMeta={
 dashboard:['Overview',LayoutDashboard],schools:['Find a School',School],admissions:['Applications',FileText],students:['Students',Users],teachers:['Teachers',GraduationCap],attendance:['Attendance',CalendarCheck],marks:['Marks & Performance',BookOpen],finance:['Finance',Wallet],spaces:['Available Spaces',Boxes],resources:['Resources',Boxes],notifications:['Notifications',MessageSquare],calendar:['School Calendar',CalendarDays],children:['My Children',Users],applications:['My Applications',FileText],fees:['School Fees',Receipt],reports:['Reports',FileText],settings:['Settings',Settings]
};

const seed={
 schools:[
  {id:'S1',name:'Hermann Gmeiner High School',centre:'3333',location:'Manzini',type:'High School',fees:3000,status:'APPROVED',admission:'OPEN',spaces:{'Form 1':20,'Form 2':10,'Form 3':15,'Form 4':12,'Form 5':13},staff:[{name:'Dr. J. Dlamini',role:'Principal'},{name:'Mr. B. Mamba',role:'Deputy Principal'},{name:'Mr. M. Nkosi',role:'Teacher',subjects:['Mathematics','English'],grades:['Form 1','Form 2']},{name:'Ms. P. Mamba',role:'Accountant'},{name:'Mrs. S. Hlophe',role:'Secretary'}]},
  {id:'S2',name:'Mbabane Valley Secondary School',centre:'4444',location:'Mbabane',type:'High School',fees:2800,status:'APPROVED',admission:'OPEN',spaces:{'Form 1':14,'Form 2':8,'Form 3':11,'Form 4':7,'Form 5':5},staff:[]},
  {id:'S3',name:'Royal Hills Primary School',centre:'5555',location:'Lobamba',type:'Primary School',fees:2200,status:'APPROVED',admission:'OPEN',spaces:{'Grade 1':12,'Grade 2':10,'Grade 3':9,'Grade 4':8,'Grade 5':10,'Grade 6':7,'Grade 7':6},staff:[]}
 ],
 pendingSchools:[],
 students:[
  {id:'ST-001',name:'Lwazi Mamba',form:'Form 1',schoolId:'S1',parentEmail:'parent@demo.sz',attendance:97,subjects:{Mathematics:{test:80,exam:84,comment:'Strong progress'},English:{test:88,exam:90,comment:'Excellent reading'}}},
  {id:'ST-002',name:'Ayanda Hlophe',form:'Form 2',schoolId:'S1',parentEmail:'parent@demo.sz',attendance:94,subjects:{Mathematics:{test:72,exam:70,comment:'Keep practising'},English:{test:75,exam:78,comment:'Good effort'}}},
  {id:'ST-003',name:'Sibusiso Dlamini',form:'Form 3',schoolId:'S1',parentEmail:'otherparent@demo.sz',attendance:87,subjects:{Mathematics:{test:61,exam:60,comment:'Needs support'}}}
 ],
 applications:[],
 payments:[
  {id:'P1',studentId:'ST-001',parentEmail:'parent@demo.sz',amount:1500,status:'APPROVED',receipt:'Demo receipt - E1500'},
  {id:'P2',studentId:'ST-002',parentEmail:'parent@demo.sz',amount:1000,status:'PENDING',receipt:'Demo receipt - E1000'}
 ],
 notifications:[{id:'N1',title:'Welcome to EduLink Eswatini',body:'This is a fictional demonstration notification.',audience:'all'}],
 calendar:[{id:'C1',title:'Parent Meeting',date:'2026-09-05',time:'14:00',details:'Main hall'}]
};

const accounts={
 'parent@demo.sz':{role:'Parent',name:'Demo Parent',schoolId:'S1'},
 'teacher@demo.sz':{role:'Teacher',name:'Mr. M. Nkosi',schoolId:'S1',subjects:['Mathematics','English'],grades:['Form 1','Form 2']},
 'accountant@demo.sz':{role:'Accountant',name:'Ms. P. Mamba',schoolId:'S1'},
 'secretary@demo.sz':{role:'Secretary',name:'Mrs. S. Hlophe',schoolId:'S1'},
 'principal@demo.sz':{role:'Principal',name:'Dr. J. Dlamini',schoolId:'S1'},
 'deputy@demo.sz':{role:'Deputy Principal',name:'Mr. B. Mamba',schoolId:'S1'},
 'admin@demo.sz':{role:'System Admin',name:'EduLink Administrator'}
};
const PASSWORD='demo123';

function loadData(){try{const x=localStorage.getItem('edulink-demo-data');return x?JSON.parse(x):seed}catch{return seed}}
function saveData(d){localStorage.setItem('edulink-demo-data',JSON.stringify(d))}
function totalSpaces(s){return Object.values(s||{}).reduce((a,b)=>a+Number(b||0),0)}
function avgStudent(st){const vals=Object.values(st.subjects||{}).flatMap(x=>[Number(x.test||0),Number(x.exam||0)]).filter(x=>Number.isFinite(x));return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):0}
function aggregate(st){return Object.values(st.subjects||{}).reduce((sum,x)=>sum+Number(x.test||0)+Number(x.exam||0),0)}
function useData(){const [data,setData]=useState(loadData);useEffect(()=>saveData(data),[data]);return [data,setData]}

function App(){
 const [data,setData]=useData(); const [user,setUser]=useState(null); const [page,setPage]=useState('home'); const [mobile,setMobile]=useState(false); const [school,setSchool]=useState(null);
 if(!user) return <Public data={data} setData={setData} onLogin={setUser} page={page} setPage={setPage} setSchool={setSchool}/>;
 const allowed=roles[user.role]||[];
 const schoolId=user.schoolId;
 return <div className="app">
  <aside className={'sidebar '+(mobile?'open':'')}><div className="brand"><div className="brandIcon"><ShieldCheck size={22}/></div><div>EduLink <span>ESWATINI</span></div></div><div className="roleBadge">{user.role}</div>
   <nav>{allowed.map(k=>{const [label,I]=navMeta[k];const display=user.role==='System Admin'&&k==='schools'?'School Management':label;return <button key={k} className={page===k?'navActive':''} onClick={()=>{setPage(k);setMobile(false)}}><I size={18}/>{display}</button>})}</nav>
   <button className="logout" onClick={()=>{setUser(null);setPage('home')}}><LogOut size={18}/>Sign out</button>
  </aside>
  <main className="main"><header className="topbar"><button className="mobileBtn" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><div><strong>{user.name}</strong><small>{user.role}{schoolId?' • '+(data.schools.find(s=>s.id===schoolId)?.name||''):''}</small></div><div className="topPill">DEMO MODE</div></header>
   <div className="content"><Page page={page} user={user} data={data} setData={setData} setPage={setPage} school={school} setSchool={setSchool}/></div>
  </main>
 </div>
}

function Public({data,setData,onLogin,page,setPage,setSchool}){
 const [search,setSearch]=useState(''); const [login,setLogin]=useState(false); const [schoolReg,setSchoolReg]=useState(false); const [selected,setSelected]=useState(null);
 const visible=data.schools.filter(s=>s.status==='APPROVED'&&(`${s.name} ${s.centre} ${s.location}`.toLowerCase().includes(search.toLowerCase())));
 if(selected) return <div className="public"><Header onLogin={()=>setLogin(true)} onSchools={()=>setSelected(null)}/><SchoolProfile school={selected} onBack={()=>setSelected(null)} onLogin={()=>setLogin(true)}/></div>;
 return <div className="public"><Header onLogin={()=>setLogin(true)} onSchools={()=>document.getElementById('schools')?.scrollIntoView({behavior:'smooth'})}/>
  <section className="hero"><div className="heroCopy"><span className="eyebrow">EDUCATION • CONNECTION • OPPORTUNITY</span><h1>One platform for <em>schools, parents and students.</em></h1><p>Find schools, check available spaces, apply online, monitor your child's progress and stay connected with school communications.</p><div className="actions"><button className="primary" onClick={()=>document.getElementById('schools')?.scrollIntoView({behavior:'smooth'})}>Find a School <ChevronRight size={17}/></button><button className="secondary" onClick={()=>setSchoolReg(true)}>Register Your School</button></div></div><div className="heroPanel"><div className="miniTop"><span>EduLink Eswatini</span><b>Prototype</b></div><div className="miniStatGrid"><div><strong>{data.schools.length}</strong><small>Registered schools</small></div><div><strong>{data.schools.reduce((a,s)=>a+totalSpaces(s.spaces),0)}</strong><small>Available spaces</small></div><div><strong>{data.applications.filter(a=>a.status==='PENDING').length}</strong><small>Active applications</small></div></div><div className="miniNote"><CheckCircle size={18}/><span>Secure role-based school management</span></div></div></section>
  <section className="publicSection" id="schools"><div className="sectionHead"><span className="eyebrow">SCHOOL DIRECTORY</span><h2>Find a school</h2><p>Search approved participating schools by name, Centre Number or location.</p></div><div className="searchBox"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search school, Centre Number or location..."/></div><div className="schoolGrid">{visible.map(s=><button className="schoolCard" key={s.id} onClick={()=>setSelected(s)}><div className="schoolIcon"><School/></div><div className="schoolCardBody"><div className="schoolLine"><span>{s.type}</span><b>{s.admission==='OPEN'?'Admissions Open':'Admissions Closed'}</b></div><h3>{s.name}</h3><p>Centre Number: {s.centre}</p><p>{s.location}</p><div className="spaceLine"><strong>{totalSpaces(s.spaces)}</strong><span>available spaces</span></div></div></button>)}</div></section>
  <section className="publicSection alt"><div className="sectionHead"><span className="eyebrow">HOW IT WORKS</span><h2>One connected education experience</h2></div><div className="featureGrid"><Feature icon="🏫" title="Find Schools" text="Discover approved schools and available spaces."/><Feature icon="📝" title="Online Applications" text="Parents submit applications and required documents online."/><Feature icon="📊" title="Child Progress" text="Parents see only their own children's marks, attendance and performance."/><Feature icon="💳" title="School Fees" text="Track balances and receipt verification through the correct school role."/></div></section>
  <footer><div className="brand"><div className="brandIcon"><ShieldCheck size={21}/></div><div>EduLink <span>ESWATINI</span></div></div><p>Fictional prototype data • Not affiliated with ECESWA or SNAT.</p></footer>
  {login&&<LoginModal accounts={accounts} onClose={()=>setLogin(false)} onLogin={u=>{setLogin(false);onLogin(u);setPage('dashboard')}}/>}
  {schoolReg&&<SchoolRegistration data={data} setData={setData} onClose={()=>setSchoolReg(false)}/>} 
 </div>
}
function Header({onLogin,onSchools}){return <header className="publicHeader"><div className="brand"><div className="brandIcon"><ShieldCheck size={22}/></div><div>EduLink <span>ESWATINI</span></div></div><nav><button onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}>Home</button><button onClick={onSchools}>Find a School</button><button onClick={()=>document.getElementById('about')?.scrollIntoView({behavior:'smooth'})}>About</button><button className="loginTop" onClick={onLogin}>Login</button></nav></header>}
function Feature({icon,title,text}){return <div className="featureCard"><div className="featureIcon">{icon}</div><h3>{title}</h3><p>{text}</p></div>}
function SchoolProfile({school,onBack,onLogin}){return <section className="profilePage"><button className="backBtn" onClick={onBack}>← Back to schools</button><div className="profileHero"><div><span className="eyebrow">APPROVED SCHOOL</span><h1>{school.name}</h1><p>Centre Number: <b>{school.centre}</b> • {school.location} • {school.type}</p></div><span className="openBadge">{school.admission==='OPEN'?'ADMISSIONS OPEN':'ADMISSIONS CLOSED'}</span></div><div className="profileGrid"><div className="infoPanel"><h3>Available spaces</h3><div className="bigNumber">{totalSpaces(school.spaces)}</div><div className="spaceRows">{Object.entries(school.spaces).map(([g,n])=><div key={g}><span>{g}</span><b>{n>0?n:'FULL'}</b></div>)}</div></div><div className="infoPanel"><h3>School fees</h3><div className="feeAmount">E {school.fees.toLocaleString()}</div><p>Demo annual school fees. Parents can apply after signing in.</p><button className="primary" onClick={onLogin}>Login to Apply</button></div></div></section>}

function LoginModal({onClose,onLogin}){const [email,setEmail]=useState('parent@demo.sz');const [pw,setPw]=useState('demo123');const [err,setErr]=useState('');return <Modal title="Login to EduLink" onClose={onClose}><p className="muted">Use a demo account for the presentation.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={pw} onChange={e=>setPw(e.target.value)}/></label><div className="demoHint">Demo password: <b>demo123</b><br/>Parent • Teacher • Accountant • Secretary • Principal • Deputy • Admin</div><button className="primary full" onClick={()=>{const a=accounts[email.trim().toLowerCase()];if(!a||pw!==PASSWORD)return setErr('Incorrect demo email or password.');onLogin({email:email.trim().toLowerCase(),...a})}}>Login</button>{err&&<div className="error">{err}</div>}</Modal>}

function SchoolRegistration({data,setData,onClose}){const [f,setF]=useState({name:'',centre:'',location:'',type:'High School',phone:'',email:'',principal:'',deputy:'',staff:''});const [done,setDone]=useState(false);function submit(){if(!f.name||!f.centre||!f.location||!f.principal)return;const staff=f.staff.split(',').map(x=>x.trim()).filter(Boolean).map(x=>({name:x,role:'Teacher'}));setData({...data,pendingSchools:[...data.pendingSchools,{...f,id:'PS-'+Date.now(),status:'PENDING',staff:[{name:f.principal,role:'Principal'},{name:f.deputy,role:'Deputy Principal'},...staff]}]});setDone(true)}return <Modal title="Register Your School" onClose={onClose}>{done?<><div className="successBox"><CheckCircle/> Registration submitted for Admin verification.</div><p className="muted">The System Admin must verify that the school exists and that the submitted information is truthful before approval.</p><button className="primary full" onClick={onClose}>Done</button></>:<><div className="formGrid"><label>School name*<input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Centre Number*<input value={f.centre} onChange={e=>setF({...f,centre:e.target.value})}/></label><label>Location*<input value={f.location} onChange={e=>setF({...f,location:e.target.value})}/></label><label>School type<select value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option>High School</option><option>Primary School</option></select></label><label>School phone<input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></label><label>School email<input value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><label>Principal name*<input value={f.principal} onChange={e=>setF({...f,principal:e.target.value})}/></label><label>Deputy Principal name<input value={f.deputy} onChange={e=>setF({...f,deputy:e.target.value})}/></label></div><label>Staff names <small>(comma separated; demo prototype)</small><input value={f.staff} onChange={e=>setF({...f,staff:e.target.value})} placeholder="Teacher names, accountant, secretary..."/></label><button className="primary full" onClick={submit}>Submit for verification</button></>}</Modal>}
function Modal({title,onClose,children}){return <div className="modalOverlay"><div className="modal"><button className="close" onClick={onClose}><X/></button><h2>{title}</h2>{children}</div></div>}

function Page({page,user,data,setData,setPage}){switch(page){case'dashboard':return <Dashboard user={user} data={data} setPage={setPage}/>;case'schools':return user.role==='System Admin'?<AdminSchools data={data} setData={setData}/>:<ParentSchools user={user} data={data} setPage={setPage}/>;case'admissions':return <Admissions user={user} data={data} setData={setData}/>;case'students':return <Students user={user} data={data}/>;case'teachers':return <Teachers user={user} data={data} setData={setData}/>;case'attendance':return <Attendance user={user} data={data} setData={setData}/>;case'marks':return <Marks user={user} data={data} setData={setData}/>;case'finance':return <Finance user={user} data={data} setData={setData}/>;case'spaces':return <Spaces user={user} data={data} setData={setData}/>;case'resources':return <Resources/>;case'notifications':return <Notifications user={user} data={data} setData={setData}/>;case'calendar':return <Calendar data={data} setData={setData} canEdit={user.role==='Secretary'||user.role==='Principal'||user.role==='Deputy Principal'}/>;case'children':return <Children user={user} data={data}/>;case'applications':return <ParentApplications user={user} data={data}/>;case'fees':return <ParentFees user={user} data={data}/>;case'reports':return <Reports user={user} data={data}/>;default:return <SettingsPage/>}}
function HeaderBlock({eyebrow,title,text,actions}){return <div className="pageHead"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{text&&<p>{text}</p>}</div>{actions}</div>}
function Stat({label,value,icon:Icon}){return <div className="statCard"><div className="statIcon"><Icon size={20}/></div><div><strong>{value}</strong><span>{label}</span></div></div>}
function Dashboard({user,data,setPage}){const school=user.schoolId?data.schools.find(s=>s.id===user.schoolId):null;const students=school?data.students.filter(x=>x.schoolId===school.id):data.students;const apps=school?data.applications.filter(x=>x.schoolId===school.id):data.applications;const pendingSchools=data.pendingSchools.length; if(user.role==='System Admin')return <><HeaderBlock eyebrow="PLATFORM ADMINISTRATION" title="EduLink Control Centre" text="Manage participating schools and keep the platform running smoothly."/><div className="statGrid"><Stat label="Registered Schools" value={data.schools.length} icon={School}/><Stat label="Pending Schools" value={pendingSchools} icon={Clock}/><Stat label="Approved Schools" value={data.schools.filter(s=>s.status==='APPROVED').length} icon={CheckCircle}/></div><Panel title="Admin responsibility"><p className="muted">Verify school existence and submitted information before approval. Platform Admin does not access academic performance, fees, attendance or school notifications.</p><button className="primary" onClick={()=>setPage('schools')}>Open School Management</button></Panel></>;
 const avg=students.length?Math.round(students.reduce((a,s)=>a+avgStudent(s),0)/students.length):0;return <><HeaderBlock eyebrow={user.role.toUpperCase()} title={school?.name||'My EduLink Workspace'} text="Live demo data updates across the authorised modules."/><div className="statGrid"><Stat label="Students" value={students.length} icon={Users}/>{['Principal','Deputy Principal'].includes(user.role)&&<Stat label="Active Applications" value={apps.filter(a=>a.status==='PENDING').length} icon={FileText}/>} {user.role!=='Accountant'&&<Stat label="Average Performance" value={avg+'%'} icon={BookOpen}/>} {user.role==='Accountant'?<Stat label="Pending Receipts" value={data.payments.filter(p=>p.status==='PENDING').length} icon={Receipt}/>:<Stat label="Available Spaces" value={school?totalSpaces(school.spaces):0} icon={Boxes}/>}</div><Panel title="Recent activity"><div className="activity"><span><CheckCircle/> Changes are saved in this browser for presentation demos.</span><span><ShieldCheck/> Access is restricted by role and school.</span><span><ChevronRight/> Use the sidebar to demonstrate the workflow.</span></div></Panel></>}
function Panel({title,children}){return <section className="panel"><div className="panelTitle"><h2>{title}</h2></div>{children}</section>}

function AdminSchools({data,setData}){const [view,setView]=useState(null);function approve(p){const school={id:'S-'+Date.now(),name:p.name,centre:p.centre,location:p.location,type:p.type,fees:3000,status:'APPROVED',admission:'OPEN',spaces:p.type==='Primary School'?{'Grade 1':20,'Grade 2':20,'Grade 3':20,'Grade 4':20,'Grade 5':20,'Grade 6':20,'Grade 7':20}:{'Form 1':20,'Form 2':20,'Form 3':20,'Form 4':20,'Form 5':20},staff:p.staff||[]};setData({...data,schools:[...data.schools,school],pendingSchools:data.pendingSchools.filter(x=>x.id!==p.id)})}function reject(p){const reason=prompt('Reason for rejection:','Information could not be verified');setData({...data,pendingSchools:data.pendingSchools.filter(x=>x.id!==p.id),notifications:[...data.notifications,{id:'N-'+Date.now(),title:'School registration rejected',body:`${p.name}: ${reason||'Not verified'}`,audience:'admin'}]})}return <><HeaderBlock eyebrow="SCHOOL MANAGEMENT" title="School verification" text="Review every registration before it becomes an approved EduLink school."/><div className="statGrid"><Stat label="Registered Schools" value={data.schools.length} icon={School}/><Stat label="Pending Schools" value={data.pendingSchools.length} icon={Clock}/><Stat label="Total Schools" value={data.schools.length} icon={Users}/></div><Panel title="Pending school registrations">{data.pendingSchools.length===0?<Empty text="No pending school registrations."/>:<Table headers={['School','Centre Number','Location','Contact','Actions']} rows={data.pendingSchools.map(p=>[<b>{p.name}</b>,p.centre,p.location,p.email||'—',<div className="rowActions"><button className="small" onClick={()=>setView(p)}><Eye size={14}/>Review</button><button className="small good" onClick={()=>approve(p)}><CheckCircle size={14}/>Approve</button><button className="small danger" onClick={()=>reject(p)}><XCircle size={14}/>Reject</button></div>])}/>}</Panel><Panel title="Registered schools">{data.schools.map(s=><div className="listRow" key={s.id}><div><b>{s.name}</b><small>Centre {s.centre} • {s.location} • {s.type}</small></div><span className="status approved">APPROVED</span></div>)}</Panel>{view&&<Modal title="Verify school registration" onClose={()=>setView(null)}><div className="verifyBox"><p><b>{view.name}</b></p><p>Centre Number: {view.centre}</p><p>Location: {view.location}</p><p>Type: {view.type}</p><p>Principal: {view.principal||'—'}</p><p>Deputy: {view.deputy||'—'}</p><p>Staff submitted: {(view.staff||[]).map(x=>x.name).join(', ')||'—'}</p></div><p className="muted">Admin must independently verify that the school exists and that submitted information is truthful before approving.</p></Modal>}</>}

function ParentSchools({user,data,setPage}){const [q,setQ]=useState('');const list=data.schools.filter(s=>s.status==='APPROVED'&&(`${s.name} ${s.centre} ${s.location}`.toLowerCase().includes(q.toLowerCase())));return <><HeaderBlock eyebrow="SCHOOL DIRECTORY" title="Find a school" text="You are already signed in. There is no second parent login required to apply."/><div className="searchBox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="School name, Centre Number or location"/></div><div className="schoolGrid">{list.map(s=><div className="schoolCard signed" key={s.id}><div className="schoolIcon"><School/></div><div className="schoolCardBody"><h3>{s.name}</h3><p>Centre {s.centre} • {s.location}</p><div className="spaceLine"><strong>{totalSpaces(s.spaces)}</strong><span>available spaces</span></div><button className="primary smallWide" onClick={()=>setPage('applications')}>Apply to this school</button></div></div>)}</div></>}

function Admissions({user,data,setData}){const schoolId=user.schoolId;const list=data.applications.filter(a=>a.schoolId===schoolId);function decide(a,status){let next={...data,applications:data.applications.map(x=>x.id===a.id?{...x,status}:x)};if(status==='APPROVED'&&a.status!=='APPROVED'){const s=data.schools.find(x=>x.id===schoolId);if(s&&Number(s.spaces[a.form]||0)>0){next.schools=data.schools.map(x=>x.id===schoolId?{...x,spaces:{...x.spaces,[a.form]:Math.max(0,Number(x.spaces[a.form])-1)}}:x)}else{alert('No available space for this grade/form.');return}}setData(next)}return <><HeaderBlock eyebrow="ADMISSIONS" title="Application management" text="Review active applications and approve, decline or wait-list them."/><Panel title="Active applications">{list.length===0?<Empty text="No applications yet. A parent application will appear here automatically."/>:<Table headers={['Applicant','Child','Grade/Form','Documents','Status','Actions']} rows={list.map(a=>[a.parentName,a.childName,a.form,<button className="small" onClick={()=>alert((a.documents||[]).map(d=>d.name).join('\n')||'No documents') }><Eye size={14}/>View</button>,<Status status={a.status}/>,<div className="rowActions"><button className="small good" onClick={()=>decide(a,'APPROVED')}>Approve</button><button className="small" onClick={()=>decide(a,'WAITLIST')}>Wait list</button><button className="small danger" onClick={()=>decide(a,'DECLINED')}>Decline</button></div>])}/>}</Panel></>}

function Students({user,data}){const list=data.students.filter(s=>s.schoolId===user.schoolId);return <><HeaderBlock eyebrow="STUDENTS" title="Student register" text="Students are grouped by Grade/Form with attendance and average performance."/><Panel title="All students"><Table headers={['Grade/Form','Student','Attendance','Average','Performance']} rows={list.sort((a,b)=>a.form.localeCompare(b.form)).map(s=>[s.form,s.name,s.attendance+'%',avgStudent(s)+'%',avgStudent(s)<50?<span className="warn">Attention</span>:<span className="goodText">On track</span>])}/></Panel></>}
function Teachers({user,data,setData}){const staff=data.schools.find(s=>s.id===user.schoolId)?.staff||[];return <><HeaderBlock eyebrow="TEACHERS" title="Teaching staff" text="Staff assigned to this school only."/><Panel title="Registered school staff">{staff.length?<Table headers={['Name','Role','Subjects','Grades/Forms']} rows={staff.map(x=>[x.name,x.role,(x.subjects||[]).join(', ')||'—',(x.grades||[]).join(', ')||'—'])}/>:<Empty text="No additional staff recorded."/>}</Panel></>}

function Attendance({user,data,setData}){const list=data.students.filter(s=>s.schoolId===user.schoolId);const [absent,setAbsent]=useState({});function save(){setData({...data,students:data.students.map(s=>{if(s.schoolId!==user.schoolId)return s;const isAbs=!!absent[s.id];const next=Math.max(0,Math.min(100,isAbs?s.attendance-1:s.attendance));return {...s,attendance:next}})});setAbsent({})}if(user.role==='Parent')return <Children user={user} data={data}/>;return <><HeaderBlock eyebrow="ATTENDANCE" title="Attendance register" text="Teachers mark absent students. Unmarked students remain present."/><Panel title="Today's register"><Table headers={['Grade/Form','Student','Current attendance','Today']} rows={list.map(s=>[s.form,s.name,s.attendance+'%',<label className="check"><input type="checkbox" checked={!!absent[s.id]} onChange={e=>setAbsent({...absent,[s.id]:e.target.checked})}/> Absent</label>])}/><button className="primary" onClick={save}>Save attendance</button></Panel></>}

function Marks({user,data,setData}){const schoolId=user.schoolId;const schoolStudents=data.students.filter(s=>s.schoolId===schoolId);const subjects=user.role==='Teacher'?(user.subjects||[]):['Mathematics','English','Chemistry','Agriculture','Physics'];const [subject,setSubject]=useState(subjects[0]);const [editing,setEditing]=useState({});function change(id,field,val){setEditing({...editing,[id]:{...(editing[id]||{}),[field]:val}})}function save(){setData({...data,students:data.students.map(s=>{const e=editing[s.id];if(!e)return s;return {...s,subjects:{...s.subjects,[subject]:{test:Number(e.test ?? (s.subjects?.[subject]?.test || 0)),exam:Number(e.exam ?? (s.subjects?.[subject]?.exam || 0)),comment:e.comment ?? (s.subjects?.[subject]?.comment || '')}}}})});setEditing({})}return <><HeaderBlock eyebrow="ACADEMIC RECORDS" title="Marks table" text={user.role==='Teacher'?'You can only enter marks for subjects and grades assigned to you.':'School-wide academic view and comments.'}/><div className="toolbar"><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s}>{s}</option>)}</select></label></div><Panel title="Student marks"><Table headers={['Form','Name','Test','Exam','Aggregate','Comment']} rows={schoolStudents.map(s=>{const cur=s.subjects?.[subject]||{};const e=editing[s.id]||{};const t=e.test??cur.test??0;const ex=e.exam??cur.exam??0;const can=user.role!=='Teacher'||(user.subjects||[]).includes(subject);return [s.form,s.name,can?<input className="cellInput" type="number" min="0" max="100" value={t} onChange={x=>change(s.id,'test',x.target.value)}/>:t,can?<input className="cellInput" type="number" min="0" max="100" value={ex} onChange={x=>change(s.id,'exam',x.target.value)}/>:ex,Number(t)+Number(ex),can?<input className="cellInput comment" value={e.comment??cur.comment??''} onChange={x=>change(s.id,'comment',x.target.value)} placeholder="Teacher/principal comment"/>:cur.comment||'—']})}/><button className="primary" onClick={save}>Save marks & comments</button></Panel><Panel title="Overall subject table"><Table headers={['Form','Name','Math','English','Chem','Agr','Physics','Aggregate']} rows={schoolStudents.map(s=>[s.form,s.name,...['Mathematics','English','Chemistry','Agriculture','Physics'].map(sub=>{const x=s.subjects?.[sub];return x?Math.round((Number(x.test||0)+Number(x.exam||0))/2)+'%':'—'}),aggregate(s)])}/></Panel></>}

function Finance({user,data,setData}){const students=data.students.filter(s=>s.schoolId===user.schoolId);function paid(s){return data.payments.filter(p=>p.studentId===s.id&&p.status==='APPROVED').reduce((a,p)=>a+Number(p.amount),0)}function approve(p,status){setData({...data,payments:data.payments.map(x=>x.id===p.id?{...x,status}:x)})}return <><HeaderBlock eyebrow="FINANCE" title="Student fee ledger" text="Academic performance is intentionally not shown to the accountant."/><Panel title="Student balances"><Table headers={['Form','Student','Total Fees','Paid','Balance','Status']} rows={students.map(s=>{const total=data.schools.find(x=>x.id===s.schoolId)?.fees||0;const p=paid(s);return [s.form,s.name,'E '+total.toLocaleString(),'E '+p.toLocaleString(),'E '+Math.max(0,total-p).toLocaleString(),p>=total?<span className="goodText">PAID</span>:<span className="warn">OUTSTANDING</span>]})}/></Panel><Panel title="Parent receipt approvals">{data.payments.filter(p=>p.status==='PENDING'&&students.some(s=>s.id===p.studentId)).length===0?<Empty text="No pending receipts."/>:<Table headers={['Student','Amount','Receipt','Action']} rows={data.payments.filter(p=>p.status==='PENDING'&&students.some(s=>s.id===p.studentId)).map(p=>{const s=students.find(x=>x.id===p.studentId);return [s?.name,'E '+p.amount,p.receipt,<div className="rowActions"><button className="small good" onClick={()=>approve(p,'APPROVED')}>Approve</button><button className="small danger" onClick={()=>approve(p,'REJECTED')}>Reject</button></div>]})}/>}</Panel></>}

function ParentApplicationForm({user,data,setData,school,onDone}){const child=data.students.find(s=>s.parentEmail===user.email)||data.students.find(s=>s.parentEmail==='parent@demo.sz');const [f,setF]=useState({childName:child?.name||'',dob:'',gender:'',previousSchool:'',form:Object.keys(school.spaces)[0]||''});const [files,setFiles]=useState([]);const [msg,setMsg]=useState('');function addFiles(e){setFiles([...files,...Array.from(e.target.files||[])])}function submit(){if(!f.childName||!f.form)return setMsg('Please complete the child and Grade/Form fields.');if(Number(school.spaces[f.form]||0)<=0)return setMsg('That Grade/Form is currently full.');const app={id:'APP-'+Date.now(),schoolId:school.id,parentEmail:user.email,parentName:user.name,childName:f.childName,dob:f.dob,gender:f.gender,previousSchool:f.previousSchool,form:f.form,status:'PENDING',documents:files.map(x=>({name:x.name,size:x.size,type:x.type})),createdAt:new Date().toISOString()};setData({...data,applications:[...data.applications,app],notifications:[...data.notifications,{id:'N-'+Date.now(),title:'New application submitted',body:`${f.childName} applied to ${school.name}`,audience:school.id}]});setMsg('Application submitted. The school will now see it in its Applications module.');setTimeout(onDone,700)}return <Modal title={`Apply to ${school.name}`} onClose={onDone}><div className="formGrid"><label>Child full name*<input value={f.childName} onChange={e=>setF({...f,childName:e.target.value})}/></label><label>Date of birth<input type="date" value={f.dob} onChange={e=>setF({...f,dob:e.target.value})}/></label><label>Gender<select value={f.gender} onChange={e=>setF({...f,gender:e.target.value})}><option value="">Select</option><option>Female</option><option>Male</option></select></label><label>Grade/Form*<select value={f.form} onChange={e=>setF({...f,form:e.target.value})}>{Object.entries(school.spaces).map(([g,n])=><option key={g} disabled={Number(n)<=0}>{g}{Number(n)<=0?' — FULL':''}</option>)}</select></label><label className="wide">Previous school<input value={f.previousSchool} onChange={e=>setF({...f,previousSchool:e.target.value})}/></label></div><div className="uploadBox"><Upload/><div><b>Required documents</b><p>Upload transcript/report and any other documents required by the school.</p></div><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png" onChange={addFiles}/></div>{files.length>0&&<div className="fileList">{files.map((x,i)=><span key={i}><FileText size={14}/>{x.name}</span>)}</div>}<button className="primary full" onClick={submit}>Submit Application</button>{msg&&<div className={msg.startsWith('Application')?'successBox':'error'}>{msg}</div>}</Modal>}

function ParentApplications({user,data}){const [open,setOpen]=useState(null);const list=data.applications.filter(a=>a.parentEmail===user.email);return <><HeaderBlock eyebrow="MY APPLICATIONS" title="Application status" text="Only applications submitted from your parent account are shown."/><Panel title="My applications">{list.length===0?<Empty text="You have no applications yet. Find a school to start an application."/>:<Table headers={['School','Child','Form','Documents','Status']} rows={list.map(a=>{const s=data.schools.find(x=>x.id===a.schoolId);return [s?.name,a.childName,a.form,(a.documents||[]).length+' document(s)',<Status status={a.status}/>]})}/>}</Panel></>}
function ParentFees({user,data}){const list=data.students.filter(s=>s.parentEmail===user.email);return <><HeaderBlock eyebrow="SCHOOL FEES" title="My children's fees"/><Panel title="Balances">{list.length?<Table headers={['Child','Total Fees','Paid','Balance']} rows={list.map(s=>{const total=data.schools.find(x=>x.id===s.schoolId)?.fees||0;const paid=data.payments.filter(p=>p.studentId===s.id&&p.status==='APPROVED').reduce((a,p)=>a+Number(p.amount),0);return [s.name,'E '+total.toLocaleString(),'E '+paid.toLocaleString(),'E '+Math.max(0,total-paid).toLocaleString()]})}/>:<Empty text="No linked children."/>}</Panel></>}
function Children({user,data}){const list=data.students.filter(s=>s.parentEmail===user.email);return <><HeaderBlock eyebrow="MY CHILDREN" title="Your children's progress" text="You can only see records linked to your parent account."/><div className="childGrid">{list.map(s=><div className="childCard" key={s.id}><div className="childHead"><div className="avatar">{s.name.charAt(0)}</div><div><h3>{s.name}</h3><p>{s.form} • {data.schools.find(x=>x.id===s.schoolId)?.name}</p></div></div><div className="childStats"><div><strong>{s.attendance}%</strong><span>Attendance</span></div><div><strong>{avgStudent(s)}%</strong><span>Average</span></div><div><strong>{aggregate(s)}</strong><span>Aggregate</span></div></div><h4>Subject performance</h4><div className="subjectMini">{Object.entries(s.subjects||{}).map(([sub,x])=><div key={sub}><span>{sub}</span><b>{Math.round((Number(x.test||0)+Number(x.exam||0))/2)}%</b><small>{x.comment||'No comment yet'}</small></div>)}</div></div>)}</div>{!list.length&&<Empty text="No children are linked to this parent account in the demo."/>}</>}
function Notifications({user,data,setData}){const relevant=data.notifications.filter(n=>n.audience==='all'||n.audience===user.schoolId||n.audience===user.email);return <><HeaderBlock eyebrow="NOTIFICATIONS" title="School communications"/><Panel title="Notifications">{relevant.map(n=><div className="notification" key={n.id}><MessageSquare/><div><b>{n.title}</b><p>{n.body}</p></div></div>)}</Panel></>}
function Calendar({data,setData,canEdit}){const [f,setF]=useState({title:'',date:'',time:'',details:''});function add(){if(!f.title||!f.date)return;setData({...data,calendar:[...data.calendar,{...f,id:'C-'+Date.now()}]});setF({title:'',date:'',time:'',details:''})}return <><HeaderBlock eyebrow="SCHOOL CALENDAR" title="School calendar" text="Shared calendar for authorised school roles."/>{canEdit&&<Panel title="Add calendar event"><div className="formGrid"><label>Event<input value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><label>Date<input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></label><label>Time<input type="time" value={f.time} onChange={e=>setF({...f,time:e.target.value})}/></label><label>Details<input value={f.details} onChange={e=>setF({...f,details:e.target.value})}/></label></div><button className="primary" onClick={add}>Add event</button></Panel>}<Panel title="Upcoming events">{data.calendar.sort((a,b)=>a.date.localeCompare(b.date)).map(c=><div className="calendarRow" key={c.id}><div className="dateBox"><b>{new Date(c.date+'T00:00:00').toLocaleDateString(undefined,{day:'2-digit'})}</b><span>{new Date(c.date+'T00:00:00').toLocaleDateString(undefined,{month:'short'})}</span></div><div><h3>{c.title}</h3><p>{c.time||'All day'} • {c.details}</p></div></div>)}</Panel></>}
function Spaces({user,data,setData}){const s=data.schools.find(x=>x.id===user.schoolId);const [spaces,setSpaces]=useState(s?.spaces||{});function save(){setData({...data,schools:data.schools.map(x=>x.id===s.id?{...x,spaces}:x)})}return <><HeaderBlock eyebrow="ADMISSIONS CAPACITY" title="Available spaces" text="Approved applications automatically reduce the selected Grade/Form space."/><Panel title={s?.name}>{Object.entries(spaces).map(([g,n])=><label className="spaceEdit" key={g}><span>{g}</span><input type="number" min="0" value={n} onChange={e=>setSpaces({...spaces,[g]:Number(e.target.value)})}/><b>{n===0?'FULL':n+' spaces'}</b></label>)}<div className="totalBar"><span>Total available</span><strong>{totalSpaces(spaces)}</strong></div><button className="primary" onClick={save}>Save capacity</button></Panel></>}
function Resources(){return <><HeaderBlock eyebrow="RESOURCES" title="School resources"/><Panel title="Demo resources"><Table headers={['Resource','Location','Quantity','Status']} rows={[["Desks",'Form 1 classroom',24,'Available'],['Chairs','Form 1 classroom',30,'Available'],['Computers','ICT Lab',20,'Available'],['Laboratory benches','Science Lab',18,'Available']]}/></Panel></>}
function Reports({user,data}){return <><HeaderBlock eyebrow="REPORTS" title="School reports"/><Panel title="Academic subject performance"><Table headers={['Subject','Average']} rows={['Mathematics','English','Chemistry','Agriculture','Physics'].map(sub=>{const vals=data.students.filter(s=>s.schoolId===user.schoolId).flatMap(s=>{const x=s.subjects?.[sub];return x?[Number(x.test||0),Number(x.exam||0)]:[]});return [sub,vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length)+'%':'—']})}/></Panel></>}
function SettingsPage(){return <><HeaderBlock eyebrow="SETTINGS" title="Prototype settings" text="Production authentication, database, storage and SMS will be connected in a future backend."/><Panel title="Architecture ready"><div className="activity"><span><ShieldCheck/> Role-based navigation</span><span><Upload/> Document upload field for applications</span><span><ClipboardList/> Shared demo data through local browser storage</span></div></Panel></>}
function Status({status}){const map={PENDING:['PENDING','pending'],APPROVED:['APPROVED','approved'],DECLINED:['DECLINED','rejected'],WAITLIST:['WAIT LIST','waitlist']};const [label,cls]=map[status]||[status.toUpperCase(),'pending'];return <span className={'status '+cls}>{label}</span>}
function Table({headers,rows}){return <div className="tableWrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
function Empty({text}){return <div className="empty"><ClipboardList size={30}/><p>{text}</p></div>}

createRoot(document.getElementById('root')).render(<App/>);
